Mark bloXroute Max Profit relay as censoring.
rocket-pool/smartnode pull request #600
Opened 2024-07-17 17:08 UTC by Darkmessage

Since December 18th 2023, bloXroute Max Profit relay is also censoring OFAC transactions.

This was announced [on Twitter here](https://x.com/bloxroute/status/1736819783520092357) and is now documented [on their website](https://docs.bloxroute.com/apis/mev-solution/mev-relay-for-validators#relay-types):

> Both two relays currently propagate all available transactions/bundles except the ones that interacted with addresses sanctioned by OFAC, and they have the same filtering requirement, although for legacy reasons, bloXroute still maintains the two relay names in parallel.

2024-07-17 17:13 UTC, Darkmessage commented
I just adjusted the setting that I found during a quick search.

But since I don't know the SmartNode code, maybe some kind of upgrade step is needed, so that the people who use non-regulated profile mode are up-to-date?
But I guess the current relays are always rebuilt and given to the client when restarting the client containers anyway, right?

2024-07-17 17:22 UTC, Darkmessage commented
Should also be updated in the docs on the website:

![image](https://github.com/user-attachments/assets/54beaf0a-a0cb-49dd-aa25-b337a59894ac)

So I also created [a PR](https://github.com/rocket-pool/docs.rocketpool.net/pull/91) for that.

2024-07-18 23:52 UTC, 0xfornax requested changes
Hey Darkmessage, thanks for the contribution!
I'd just keep current the names instead of using 1 and 2, since their docs still refer to the original names. We can keep the warning that both relays propagate the same txs.

2024-07-19 20:39 UTC, 0xfornax approved these changes

2024-07-19 20:39 UTC, merged